### ISSUE TITLE
Issue with integrating new S1_mosaic 

### ISSUE THREAD

**Issue by nicholasmetherall** [digitalearthpacific/mineral-resource-detection#11]
When integrating the new S1 mosaic, the band options are do not yet have mean_vv / mean_vh usually called mean_vv_vh 

![image](https://github.com/digitalearthpacific/mineral-resource-detection/assets/67347387/479a94c7-fd00-4aa8-b8dc-449f370f16ac)

So I have calculated this using two approaches / formula including the way we do for S2 and the way we did for S1 in the past... 

![image](https://github.com/digitalearthpacific/mineral-resource-detection/assets/67347387/621139e4-f324-4a0f-ae7a-fe37eb5d8297)

However, at the next stage to load items for the bbox of Fiji , we now don't have the band aliases needed to proceed. This is a new error that was not encountered in the past. I have tried to troubleshoot this by updating the s1_dataset and mean_s1 xarrays but this does not change the items_s1 dataset. 

![image](https://github.com/digitalearthpacific/mineral-resource-detection/assets/67347387/385f8493-ca28-470e-ada5-87d45a1f326c)
![image](https://github.com/digitalearthpacific/mineral-resource-detection/assets/67347387/dbd39e50-d9dc-4170-945e-745a31610262)

Any advice would be great.

**Comment by nicholasmetherall** [comment]
Script for replication: https://github.com/digitalearthpacific/mineral-resource-detection/blob/nicholasmetherall-patch-2/MRD_S2_RandomForest_16.ipynb

**Comment by alexgleith** [comment]
Nick, there's three different sets of code you're sharing.

When you share snippets, if you can do it wrapped with three of these ``` then I can help edit it. Screenshots are harder.

To calculate `vv / vh` you should be able to do this:

```python
# Load the data
data_s1 = load(
    items_s1,
    bbox=fiji_bbox,
    resolution=10,,
    bands=["mean_vv", "mean_vh"],
    chunks={"x":4000, "y":4000}
).squeeze("time")

# Mask the nodata values
data_s1 = data_s1.where(data_s1 != -32768)

# Calculate the vv / vh means
data_s1["mean_vv_vh"] = data_s1.mean_vv / data_s1.mean_vh

# Check what we have
data_s1
```

**Comment by nicholasmetherall** [comment]
This works thanks, Alex
