### ISSUE TITLE
Analytics hub (kernel) continues to frequently restart

### ISSUE THREAD

**Issue by nicholasmetherall** [digitalearthpacific/mineral-resource-detection#3]
After approximately 5 - 20 mins, my analytics hub instance will timeout prompting to restart the kernel. This has slowed down workflows from Nov 2023-Jan 2024.

**Comment by alexgleith** [comment]
I've increased the timeout to `30` minutes. https://github.com/digitalearthpacific/planetary-computer-hub/commit/1a8f96c581181695dbe69b30c2422d05592739b2
