### ISSUE TITLE
How best to incorporate new classes into if else expression / how to incorporate a lookup table

### ISSUE THREAD

**Issue by nicholasmetherall** [digitalearthpacific/mineral-resource-detection#4]
Seeking advice on how best to incorporate the other lulc classes into this if else expression. 

projected_training_data = tdata.to_crs("EPSG:3832")
training_array = []

```
def get_training_data(id_row):
    _, row = id_row
    cls = row["lulc_class"]
    # Add more classes as integers here.
    # Maybe use a look-up table.
    cls_id = 1 if cls == "bare_land" else 0
    # cls_id = 2 if cls == "forest"
    # cls_id = 3 if cls == "crops"
    # cls_id = 4 if cls == "grassland"
    # cls_id = 5 if cls == "settlements"
    # cls_id = 6 if cls == "mangroves"
    # cls_id = 7 if cls == "water" else 0
    id = row["id"]
    geom = row["geometry"]

    # Get xarray values at the point
    x = merged.sel(x=geom.x, y=geom.y, method="nearest").compute()
    one_point = [id] + [cls_id] + [float(v) for v in x.values()]
    return one_point

with ThreadPoolExecutor(max_workers=10) as executor:
    training_array = list(executor.map(get_training_data, projected_training_data.iterrows()))

print(f"Fetched data for {len(training_array)} training points")
```

![image](https://github.com/digitalearthpacific/mineral-resource-detection/assets/67347387/3c007530-446b-4649-bf65-47f8c7604f24)

**Comment by alexgleith** [comment]
You're best off having a lookup table.

Something like this:

``` python
lookup = {
    "bare_land": 1,
    "forest": 2,
}

# Get the class, and default to 0 if it's not in the lookup table
cls_id = lookup.get(cls, 0)
```

Doing lots of `if/else` statements is ugly!

**Comment by alexgleith** [comment]
Did this resolve your problem, @nicholasmetherall?

**Comment by nicholasmetherall** [comment]
Yes it did thanks! I had some indexing errors but managed to fix them and now I'm trying to put the hex colours into the dictionary too and try to get the output map to visualise each of the now seven classes rather than the probability of one class. Or should I still aim to just do the probability of one class?

**Comment by alexgleith** [comment]
Hmm, I don't know how the probability works. Maybe it's the probability of the predicted class?

Do you know how to plot the actual predicted class?

**Comment by alexgleith** [comment]
I'm guessing you already know, but you can plot the predictions with something like:

`cleaned_predictions.lu_lc.plot.imshow(size=10)`

You can define colours for each class, of course. Just needs a fancy colour map.

**Comment by alexgleith** [comment]
Anyhow I'll close this issue. Ping me on Slack tomorrow or raise another issue if you need more help.

**Comment by nicholasmetherall** [comment]
For my next step, I am trying to export the cleaned_predicitions.tif and explore it into qgis to see how they look. I tried to explore in the notebook but have to input `from model import add_image_values, get_model_prediction, get_overlay` however, we don't have the 'model' module to do this. Maybe I could use leafmap? Or maybe will just stick to qgis

**Comment by alexgleith** [comment]
If you're exporting a .tif, then you should view it in QGIS.

If you want to visualise in the notebook, you can either keep using the `data.band.plot` functions.

(You can view on an interactive map, but it's a bit tricky to do. [Example here](https://odc-geo.readthedocs.io/en/latest/raster-tools.html#plotting-on-a-map).)
