### ISSUE TITLE
Kernel dies when working with sentinel at 10m resolution

### ISSUE THREAD

**Issue by nicholasmetherall** [digitalearthpacific/mineral-resource-detection#6]
The workflow loads in S2 data including all bands but we have been working with `resolution = 100` up until this point. In order for me to assess the model outputs I need to work with `resolution = 10`  however, whenever I decrease this 100 to 10, and run the code the kernel dies. If needed, you can replicate this error by using the patch-1 branch of the repository and changing resolution to 10. 

```
bands = [
    "B02",
    "B03",
    "B04",
    "B05",
    "B06",
    "B07",
    "B08",
    "B8A",
    "B11",
    "B12",
    "emad",
    "bcmad",
    "smad",
]

data = load(
    items,
    measurements=bands,
    resolution=10,
    chunks={"x": 100, "y": 100, "time": 1},
)

data = data.squeeze("time")

data
```

![image](https://github.com/digitalearthpacific/mineral-resource-detection/assets/67347387/19261612-ff70-440b-9be3-97989fdf57d6)

**Comment by alexgleith** [comment]
This means it ran out of memory.

I suggest that you do the training on the whole of Viti Levu, but then run your test/model on a smaller region.

If you really want to keep doing it on the whole dataset, I can give you a larger workspace

**Comment by nicholasmetherall** [comment]
This makes sense. Will try to run/test the model in a smaller area.

**Comment by alexgleith** [comment]
For the training, make your array the same way as before, but don't run `compute()` on it. That will mean that each point will be queried on a dataset that's computed on the fly.

Also, the other way to do this is to use a Dask cluster, and use `persist()` instead of `compute()`, which will load it into memory, but on the cluster instead of on your machine.

**Comment by nicholasmetherall** [comment]
Trying this now... Commenting out compute() functions in two parts of the notebook where it appears. 

**1. At the merge stage**
```
# Merge datasets # commenting out .compute() functions

**merged = data.update(mean_s1)#.compute()**
merged
```


  2. After defining the lookup table dictionary
```
    lookup = {
        "bare_land": 1,
        "forest": 2,
        "crops": 3,
        "grassland": 4,
        "settlements": 5,
        "mangroves": 6,
        "water": 7,
    }
    
    id = row["id"]
    geom = row["geometry"]
    
# Get the class, and default to 0 if it's not in the lookup table
    cls_id = lookup.get(cls, 0)

    row = id_row

    # Get xarray values at the point
    **x = merged.sel(x=geom.x, y=geom.y, method="nearest")#.compute()**
    one_point = [id] + [cls_id] + [float(v) for v in x.values()]
    return one_point

with ThreadPoolExecutor(max_workers=10) as executor:
    training_array = list(executor.map(get_training_data, projected_training_data.iterrows()))

print(f"Fetched data for {len(training_array)} training points")

```

**Comment by nicholasmetherall** [comment]
However, even without computing on the fly, I am still getting the "kernel has died" message. So not sure how best to approach this.
